// Render a captioned screenshot walkthrough, not a real-time recording.
const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),{pathToFileURL}=require('url'),{execFileSync}=require('child_process');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'dist/promotion');
const frames=[
 ['Record from your menu bar','Enable Auto for supported calls. The App Store edition asks first by default.','menu-idle.webp'],
 ['Follow the conversation','See the transcript and speakers while the meeting is happening.','document-transcript.webp'],
 ['Leave with the next steps','Review the summary and action items. Save notes as Markdown.','document-summary.webp'],
 ['Keep your recordings together','Choose iCloud Drive to share recordings with iPhone and iPad.','ipad-transcript.webp']
];
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
(async()=>{fs.mkdirSync(out,{recursive:true});fs.mkdirSync(path.join(root,'site/media'),{recursive:true});const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage({viewport:{width:1920,height:1080},deviceScaleFactor:1});for(let i=0;i<frames.length;i++){const [title,sub,img]=frames[i];const file=path.join(out,`frame-${i}.html`);fs.writeFileSync(file,`<!doctype html><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:#100e17;color:#f7f5ff;font-family:-apple-system,BlinkMacSystemFont,sans-serif}.frame{height:1080px;padding:55px 80px;display:grid;grid-template-columns:650px 1fr;gap:70px;align-items:center;background:radial-gradient(ellipse at 80% 50%,#342345,transparent 65%)}header{display:flex;gap:20px;align-items:center;font-size:30px;font-weight:600}header img{width:65px;height:65px;border-radius:15px}h1{font-size:72px;line-height:1.08;letter-spacing:-2px;margin:75px 0 28px}p{font-size:31px;line-height:1.5;color:#c8bfd6}.screen{width:100%;height:790px;object-fit:contain;filter:drop-shadow(0 15px 35px #0006)}footer{position:absolute;bottom:40px;left:80px;right:80px;display:flex;justify-content:space-between;color:#b3a6c7;font-size:22px}.step{color:#bfa2ff;font-size:24px;letter-spacing:3px;margin-top:45px}</style><section class="frame"><div><header><img src="${pathToFileURL(path.join(root,'docs/assets/icon.png')).href}">Transcripts</header><div class="step">${i+1} / 4 · WORKFLOW PREVIEW</div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div><img class="screen" src="${pathToFileURL(path.join(root,'docs/guide/images',img)).href}" alt="${esc(title)}"></section><footer><span>Sample screenshots · Steps condensed · Processing time varies</span><span>transcripts.doughatcher.com</span></footer>`);await p.goto(pathToFileURL(file).href);await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));});await p.screenshot({path:path.join(out,`frame-${i}.png`)});}
}finally{await b.close()}
fs.writeFileSync(path.join(out,'frames.txt'),frames.map((_,i)=>`file '${path.join(out,`frame-${i}.png`)}'\nduration 7`).join('\n')+`\nfile '${path.join(out,'frame-3.png')}'\n`);
execFileSync('ffmpeg',['-y','-loglevel','error','-f','concat','-safe','0','-i',path.join(out,'frames.txt'),'-t','28','-r','24','-c:v','libx264','-pix_fmt','yuv420p','-crf','21','-movflags','+faststart',path.join(root,'site/media/transcripts-walkthrough.mp4')],{stdio:'inherit'});
fs.copyFileSync(path.join(out,'frame-0.png'),path.join(root,'site/media/transcripts-walkthrough.png'));console.log('Rendered 28-second, 1920×1080 captioned walkthrough.');})();
